name: ci
on:
  gollum
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          path: base
      - name: Checkout wiki
        uses: actions/checkout@v4
        with:
          path: wiki
          repository: "${{ github.repository }}.wiki"
      - run: ls -alR
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install mkdocs-material mdx_truly_sane_lists
      - run: mkdocs gh-deploy --force
